spring.application.name=spring-project-mvc

spring.datasource.url = jdbc:postgresql://localhost:5432/javaproject2
spring.datasource.username = postgres
spring.datasource.password = 0000

spring.jpa.hibernate.ddl-auto = update

spring.datasource.hikari.auto-commit = false
